# Generated by Django 3.2.2 on 2021-05-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordRole',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-position'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('KICK', 'Kick'), ('BAN', 'Ban'), ('ASSIGN_ROLE', 'Assign Role'), ('REMOVE_ROLE', 'Remove Role')], max_length=255)),
                ('members_ids', models.JSONField()),
                ('roles_ids', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('IN_QUEUE', 'In Queue'), ('STARTED', 'Started'), ('FINISHED', 'Finished'), ('FAILED', 'Failed')], default='IN_QUEUE', max_length=255)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscordMember',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('bot', models.BooleanField(default=False)),
                ('avatar_url', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('discriminator', models.CharField(max_length=255)),
                ('engagement_score', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0)),
                ('messages_count', models.IntegerField(default=0)),
                ('age_of_account', models.CharField(max_length=255)),
                ('nick', models.CharField(blank=True, max_length=255, null=True)),
                ('pending', models.BooleanField(default=False)),
                ('premium_since', models.DateTimeField(blank=True, null=True)),
                ('raw_status', models.CharField(max_length=255)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('roles', models.ManyToManyField(blank=True, related_name='members', to='discord.DiscordRole')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
