# Generated by Django 3.2.2 on 2021-05-28 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discordmember',
            name='raw_status',
        ),
    ]
