# Generated by Django 3.2.4 on 2022-09-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discord", "0002_remove_discordmember_raw_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="discordmember",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
